---
abstract: 'Perl extension for showing/modifying JPEG (meta)data.'
author:
  - 'Stefano Bettelli <bettelli@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.140640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Image-MetaData-JPEG
no_index:
  directory:
    - t
    - inc
requires: {}
version: '0.156'
